### PR TITLE
update doctest.h to v2.4.6

### LINKED ISSUE #708: v1.3.0 fails to build on Fedora 35
From https://bugzilla.redhat.com/show_bug.cgi?id=1987402 / https://koji.fedoraproject.org/koji/taskinfo?taskID=72330774
```
[ 48%] Building CXX object sandbox/CMakeFiles/sandbox.dir/sandbox.cpp.o
cd /builddir/build/BUILD/cereal-1.3.0/redhat-linux-build/sandbox && /usr/bin/g++  -I/builddir/build/BUILD/cereal-1.3.0/./include -I/builddir/build/BUILD/cereal-1.3.0/sandbox/sandbox_shared_lib -Wall -g -Wextra -Wshadow -pedantic -Wold-style-cast -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -mbranch-protection=standard -fasynchronous-unwind-tables -fstack-clash-protection -std=gnu++11 -MD -MT sandbox/CMakeFiles/sandbox.dir/sandbox.cpp.o -MF CMakeFiles/sandbox.dir/sandbox.cpp.o.d -o CMakeFiles/sandbox.dir/sandbox.cpp.o -c /builddir/build/BUILD/cereal-1.3.0/sandbox/sandbox.cpp
In file included from /builddir/build/BUILD/cereal-1.3.0/unittests/common.hpp:59,
                 from /builddir/build/BUILD/cereal-1.3.0/unittests/pair.hpp:29,
                 from /builddir/build/BUILD/cereal-1.3.0/unittests/pair.cpp:28:
/builddir/build/BUILD/cereal-1.3.0/unittests/doctest.h:4021:47: error: size of array 'altStackMem' is not an integral constant-expression
 4021 |         static char             altStackMem[4 * SIGSTKSZ];
      |            
```

Build here: [build.log.txt](https://github.com/USCiLab/cereal/files/6903337/build.log.txt)

### PR DESCRIPTION
**Pull request by junghans**
Fix #708

### CODE REVIEW

**Comment by AzothAmmo** [comment]
I don't think this will pass with the early C++ compilers, I had a branch a while ago to fix this upstream with doctest but haven't sent in the MR for it: https://github.com/AzothAmmo/doctest/commit/0db23493d89e449540d909837e6eee2c1b8f572d

**Comment by junghans** [comment]
And the currently bundled version doesn't pass with recent compilers (see #708). Maybe you can update to a version in between? Or bundle a patched version?

**Comment by AzothAmmo** [comment]
Good point - I'll see if rebasing my changes to the latest doctest fixes both.

**Comment by AzothAmmo** [comment]
fixed by #716

**Pull request closed without merging**
