### PR TITLE
Changed serialised index type of std::variant to std::int32_t

### PR DESCRIPTION
**Pull request by patrikhuber**
This makes saving & loading std::variant cross-platform.

### CODE REVIEW

**Comment by patrikhuber** [comment]
Here's the basic change, as discussed in #473.

A few notes/comments:

* The function and template argument (`int target` and `int N`) are both `int`s. I am not sure whether this may now result in a type-conversion/narrowing warning if `std::uint32_t` is not `int`. But that would probably be only on exotic platforms? And previously it might have generated a warning too because `std::size_t` is probably not `int` on many platforms.

* I can't see a unit test for variant, i.e. no `test_variant`. Shall I copy & paste `test_boost_variant` here and add that?

**Comment by patrikhuber** [comment]
I think something is not quite right yet with a88e1c7dfd2f1f1323694932df8c314af8f1777e. I've got VS2017 15.6, I confirmed that `/std:c++17` is enabled for `test_cpp17_variant`, but my `_MSVC_LANG` is `201403L`, not `201703L`.
Also I think `test_cpp17_variant`, here: https://github.com/USCiLab/cereal/blob/develop/unittests/cpp17/variant.cpp#L32 should either test for `_MSVC_LANG` too or use `CEREAL_HAS_CPP17` for the test (and the same for the `.hpp` file).
But either of these will not help as `_MSVC_LANG` is `201403L` for me, even with `/std:c++17`.

**Comment by patrikhuber** [comment]
Okay, it seems the IDE is giving me the wrong tooltip value for `_MSVC_LANG`. It is indeed `201703L`.
Now I am just still confused why `CEREAL_HAS_CPP17 ` is not set if I include macros.hpp in the variant test .cpp file.

I am also confused why there is a .cpp and a .hpp file in the cpp17 test folder. The .hpp file seems to be never included, and both files have similar contents. What am I missing?

I also seem to have a problem that none of the tests seem to compile anymore... `Severity	Code	Description	Project	File	Line	Suppression State
Error	C2220	warning treated as error - no 'object' file generated	test_vector	cereal\include\cereal\external\rapidjson\document.h	110	
`. I got one of them to run an hour ago, and didn't really change much since. Hmm.

**Comment by patrikhuber** [comment]
Okay, I think this is ready to merge. But please have a look at my comments above (the ones that are not strike-through). First and foremost I think we need to replace more instances of `#if __cplusplus >= 201703L` with the added `_MSVC_LANG` check.
Second, I really don't understand why there is a .cpp and .hpp file to each test, but maybe that's irrelevant.
I also really do not understand why `CEREAL_HAS_CPP17` seems not get defined on my platform if I include `"cereal/macros.hpp"` in the unittest, even though if I `#pragma message("_MSVC_LANG=" BOOST_PP_STRINGIZE(_MSVC_LANG))` it shows as `201703L`.

**Comment by AzothAmmo** [comment]
Do you think there should be some documentation somewhere about how to turn on the C++17 tests? Since it's only for building the tests, maybe it would be sufficient as a comment in the CMakeLists.

Regarding the template parameter, hard to say what the best thing to do here is. I think most likely it will be fine left as `int` - this can always be changed later if it is ever an issue; it shouldn't ever be a breaking change.

The .hpp/.cpp is an oversight on my part - the original PR had the tests in the .cpp but the preferred way is to have the test logic in the .hpp and instantiate it in the .cpp, I'll fix that up.

You are right on the checks for C++17, they all need to be updated to have the MSVC friendly check.

**Comment by patrikhuber** [comment]
> Do you think there should be some documentation somewhere about how to turn on the C++17 tests? Since it's only for building the tests, maybe it would be sufficient as a comment in the CMakeLists.

Hmm yea, really not sure. Maybe if there was a `CEREAL_USE_CPP17` flag or something, it would be a bit more obvious. But adding such a flag just for people that run the tests (mainly library developers I guess) may be a bit overkill too. Maybe just leave it I guess. I stumbled upon it but it's not too hard to figure out. I mainly missed it I think because they were in a subdirectory, and I had already scrolled down looking for something like `test_*optional*` - so I was just a bit blind :)

Ok great, yep agree w.r.t. the template params!

I think if you could fix the .hpp/.cpp part that would be great.
I can update the checks to be MSVC friendly next week - I'll do that in a separate PR, so that it's not in the way of merging this one.

**Pull request merged**
