### PR TITLE
Github actions for Linux and macOS

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by AzothAmmo** [comment]
Really nice! Relates #712, #726

**Comment by isuruf** [comment]
@AzothAmmo, I've added macOS CI here

**Comment by crazyhappygame** [comment]
@isuruf @AzothAmmo  It looks like github action are no setup for this repo. Only appveyor check is running

**Comment by AzothAmmo** [comment]
Will likely merge this together with #716

**Comment by AzothAmmo** [comment]
merged as part of #716

**Pull request closed without merging**
