### PR TITLE
Issue 315: making cereal thread safe

### PR DESCRIPTION
**Pull request by ChrisBFX**
I've found two place which manipulate static objects in an unsafe manner:
`Versions::find()` in helpers.hpp
`PolymorphicVirtualCaster()` in polymorphic_impl.hpp

These are now guarded by `std::unique_lock` and `std::mutex`. These guards are enabled with the new compile define CEREAL_THREAD_SAFE or the cmake define THREAD_SAFE (default off to maintain backwards compatibility)

### CODE REVIEW

**Comment by AzothAmmo** [comment]
Looks good at first glance, I'll try and test this out and merge asap. Do you think these are the only two places we need to add a mutex? I'll look around myself when I go to merge this.

**Comment by AzothAmmo** [comment]
I'm thinking of moving the mutex locking over to the `getInstance()` function of `StaticObject`. I feel like this is the safest option to take here since these are all global objects. 

It may be the case that this causes some extra locks, mostly when cereal is doing its initial set-up, but it catches all potential shared accesses in a clean way that doesn't involve any thought when writing future code for cereal.

Another change I'm going to make is to also add your preprocessor definition to `cereal/macros.hpp`, since users may not always be using CMAKE to handle compilation.

**Comment by AzothAmmo** [comment]
see discussion #315, #210

**Comment by ChrisBFX** [comment]
> I'm thinking of moving the mutex locking over to the getInstance() function of StaticObject. I feel like this is the safest option to take here since these are all global objects. 

I'm not sure this is possible as this would only guard the creation and returning of the object, but would not prevent two threads changing the same instance of a StaticObject.

**Comment by AzothAmmo** [comment]
You're correct. Only thing I'm debating is whether it would look nicer to have an interface that would allow something like

```cpp
auto lock = StaticObject<InputBindingMap<Archive>>::lock();
```

versus the need to have a lot of `#ifdef` in code.

**Comment by ChrisBFX** [comment]
Yes, that's a lot better.

**Comment by AzothAmmo** [comment]
Try out develop and let me know how this works out. I added some tests to try and capture the threading but I don't know if they do a good job; I wasn't able to create any errors with them.

**Comment by ChrisBFX** [comment]
Works for me. :+1: 
The tests run without errors with the new compile flag and fail otherwise (i commented the #ifdef out in the tests to see what happens), so I guess they are good enough.

**Pull request merged**
