### PR TITLE
Fix test compilation on ARM based platform

### PR DESCRIPTION
**Pull request by kallehuttunen**

### CODE REVIEW

**Comment by mr-c** [comment]
A new package of cereal with this pull request incorporated is making its way through the Debian builds cluster: https://buildd.debian.org/status/package.php?p=libcereal

So far, so good!

**Comment by mr-c** [comment]
I can confirm successful builds for kfreebsd-amd64, mips64el, ppc64, and x32 in addition to the previously successful builds on amd64, arm64, armel, armhf, i386, mips, mipsel, powerpc, ppc64el, and s390x.

Still waiting on: alpha, hppa, hurd-i386, kfreebsd-i386, m68k, sh4, sparc64

**Comment by AzothAmmo** [comment]
Looks good from what I can tell, do update on the status of those other builds or if anything in this needs to change.

**Comment by mr-c** [comment]
Success on the remaining official platforms: alpha, hppa, hurd-i386, kfreebsd-i386, m68k, sh4, sparc64

Unofficial platforms powerpcse and sh4 had issues but they don't appear to be cereal's fault.

Thanks for the merge!

**Pull request merged**
