### PR TITLE
AppVeyor CI integration

### LINKED ISSUE #126: Set up AppVeyor CI for Visual Studio
Same thing as travis but for Windows.

### PR DESCRIPTION
**Pull request by tusharpm**
Fixes #126. Addresses the Windows/Visual Studio requirements in #329.

The changes are for the tests which were failing (or not running) on Windows.
- Replaced `run_portability_test.sh` with the cross-platform equivalent `run_portability_test.cmake`.
- `test_polymorphic` was failing for Windows: threw `cereal::Exception` from `PolymorphicCasters`. Followed the recommendation given in the exception's message.
  - Need to check if this is the right way to resolve this - defer to collaborators' comments.
- Added the AppVeyor configuration (`appveyor.yml`) and script file (`scripts/appveyor.bat`) to build and run the unittests in all combinations of the following:
  - Configurations: `Debug` and `Release`
  - Platforms: `Win32` and `x64` - Portability tests are run only on `x64` though.
  - Visual Studio: `2013 (12)` and `2015 (14)`.
  - Need confirmation if these are necessary/sufficient - or if some need to be added/removed.

A sample build is available at https://ci.appveyor.com/project/tusharpm/cereal/build/1.2.19.

### CODE REVIEW

**Comment by AzothAmmo** [comment]
Thanks for this, I'll work on giving you proper feedback and integrating it this weekend.

**Comment by leica-andreash** [comment]
Soon VS2017 ;)

**Comment by Trass3r** [comment]
Soon VS2017 ;)

**Comment by tusharpm** [comment]
I agree, hopefully it'll be soon - I read about some cool things coming this release.
I would however like to wait for the infrastructure to stabilize: CMake generators, AppVeyor build systems, etc. before adding it here.
If all goes right, it should only be a few lines (I count 4) to be added here.

**Comment by AzothAmmo** [comment]
@tusharpm I've looked over this and everything looks good. 

I do have a request if you are able, otherwise I'll figure this out on my own time after merging your PR. 

I am planning on merging the [develop_doctest](https://github.com/USCiLab/cereal/tree/develop_doctest) branch that removes the requirement of boost_test in favor of doctest. Would you be able to update/recreate this pull request against `develop_doctest`? I'm not sure if it will simplify anything, but it will certainly make building on Windows less of a burden.

**Comment by tusharpm** [comment]
I would like to help; Can you please elaborate on what needs to change?

I understand the idea of removing boost test framework, and using doctest instead. But these changes would still be necessary as the dependency on boost serialization library for the performance test remains. If needed, I can make it optional (off by default?). It seems like a good idea to keep the boost bindings in the AppVeyor scripts for that at least.

Alternatively, you can proceed with the `develop_doctest` merge, and I can rebase my changes on top of that - an added benefit would be to not have to modify the appveyor config to build branches other than develop.

**Comment by AzothAmmo** [comment]
I'll go ahead with the merge first - I'm not sure if much of anything will need to change in regards to appveyor to be honest. I'll post back here when I've done that.

I do need to test and see why changes were necessary to make the polymorphic test compile on windows (https://github.com/USCiLab/cereal/pull/373/commits/d496b726835e82365a112833c6bd260cad05b2ca).

**Comment by AzothAmmo** [comment]
I've merged the doctest branch into develop.

**Comment by AzothAmmo** [comment]
Merged! I still need to investigate why Windows needed that modification to the polymorphic test. After that is done I can push all of this out as part of the next release.

**Pull request merged**
