### PR TITLE
Current rapidjson

### PR DESCRIPTION
**Pull request by m7thon**
EDIT Feb 17, 2016 (update to newest cereal and rapidjson):

This updates rapidjson to the current master and discards the modifications made by cereal. The differences to the previously included version of rapidjson are, as far as I can tell:

* The `precision` for double output has a different meaning. Currently rapidjson supports "truncated" double output, e.g., a precision of 2 means: 0.1285 -> 0.12, 0.004 -> 0.0, 1.23 e-7 -> 0.0. 

* I modified the current rapidjson to support writing and parsing of `nan`, `inf` and `-inf` doubles. This is a non-standard json extension that rapidjson currently does not support (but may in the future). Note that the ability to parsing `-inf` seems to be a new feature for cereal.

* `long double`, `long long`, and `unsigned long long` are no longer handled in rapidjson. However, it seems this is now handled by cereal anyway by writing these types as strings.

The file `json.hpp` is modified only minimally to work with the current rapidjson. Importantly, the parser is given the `rapidjson::kParseFullPrecisionFlag`, which means that double values are parsed in full precision (AKA correctly). This ensures that the roundtrip C++ -> json -> C++ works for all doubles.

### CODE REVIEW

**Comment by AzothAmmo** [comment]
I'll look at this in the near future since I have a little more time for cereal right now - looks like automated tests are failing but I would sort this out in a merge.  This was on my list of things to do (see #82) so if this looks good and integrates well that'd be a great help.

**Comment by m7thon** [comment]
Compilation just gives one harmless `-Wshadow` error in rapidjson/reader.h line 752. You'll have to see how you want to deal with it.

Disabling `-Werror` as I have done above is probably not what you want to do ;-)

**Comment by m7thon** [comment]
By the way, it seems your CI build doesn't actually run your unit tests, just compiles them. Is that intended?

**Comment by AzothAmmo** [comment]
They get run after compilation.

-----Original Message-----

**Comment by bagobor** [comment]
'rapidjson/filewritestream.h' - file is absent in latest rapidjson packege.

**Comment by m7thon** [comment]
@bagobor Do you mean filestream.h ? This has been replaced by filereadstream.h and filewritestream.h, and I think these now work slightly differently. You can have a look at the rapidjson docs [here](https://github.com/miloyip/rapidjson/blob/master/doc/stream.md#file-streams-filestreams).

But this (filestream.h) was not used by cereal anyway.

**Comment by bagobor** [comment]
@m7thon I'm very sorry ( was incorrect 'paste'), I meant file 'rapidjson/genericstream.h'

**Comment by m7thon** [comment]
Ah yes. But you can use the old file. I updated it to match the example given in the current rapidjson documentation, and use the RAPIDJSON... namespace macros.

**Pull request closed without merging**
